AssertionErrorString = "Assertion error:"
AssertionErrorTypesDoNotMatchString = "does not match type"
AssertionErrorStringsDoNotMatchString = "does not match "
AssertionErrorNumbersDoNotMatchString = "does not match "
AssertionErrorElementIsNotInString = "is not in"
AssertionErrorElementIsInString = "is already in"
AssertionErrorIsNotNoneString = "is 'None'"
AssertionErrorDifferenceDoesNotMatchString = "difference between end index and beginning index does not equal"
AssertionErrorTypeIsNotSubclassString = "is not a subclass of"
AssertionErrorListLengthsDoNotMatchString = "length does not match length of"

EmptyNameString = ""
DataTypeSeparatorString = "-"
NewTaskFrameString = "Task Frame "
GenericDataTypeNameString = "Generic"
ImpedanceDataTypeNameString = "Impedance"
FrequencyDataTypeNameString = "Frequency"
