client_config_backend: settings
client_config:
client_id: 203034594314-quub60eokv00cs9emvrcu7o9pcrb5uql.apps.googleusercontent.com
client_secret: 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
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token:
Trueoauth_scope:
- https://www.googleapis.com/auth/drive.file